### ISSUE TITLE
Feature request | Song finder | pro feature

### ISSUE THREAD

**Issue by NER-Alliance** [statsfm/web#19]
I hope you are accepting feature requests and that this is the right repository for it.

### What purpose does it serve?

Everyone knows the moment, when you want to listen to a song but can't remember its name. Googleing lyrics or humming it to alexa often works, but sometimes you cannot remember enough of it to find it that way either. So what about you listening history? That thing is huge but it _is_ there. Somewhere...

### How does it work?

We start off by taking every song in the full Spotify history of the user. (Full history is required) Then we strip away all useless information. Left should be only title, artist and primary genre. Now we only show the first 50 or so results, in order to keep it fast. Then, the user can remove either artist, genre or singular songs - stripping the list down until they find the song. Done!

**Comment by stijnvdkolk** [comment]
You should keep an eye out for https://swipefy.app!
